export {
  addRemote,
  addWorktree,
  branchExists,
  commitAll,
  configLocal,
  createBranch,
  createOrphanSafe,
  deleteBranch,
  diffNameOnly,
  execGit,
  fetch,
  fetchAndFastForwardBranch,
  findConflictingParentRef,
  getBranch,
  getHead,
  GitError,
  initRepo,
  isRepo,
  mergeFastForward,
  push,
  rebase,
  removeWorktree,
  resolveRemoteTrackingRef,
  statusPorcelain,
} from './git';
export type { GitExecResult } from './git';
