/**
 * @deprecated Import entity DTOs from `@shared/entities` / `@gojo/contracts`.
 * Re-export kept for daemon call sites during the S1 migration.
 */
export type {
  Agent,
  Attempt,
  AttemptState,
  AuditEvent,
  CreateAgentInput,
  CreateAttemptInput,
  CreateAuditEventInput,
  CreateProfileInput,
  CreateProjectInput,
  CreateRunRecordInput as CreateRunInput,
  CreateScheduleInput,
  Profile,
  Project,
  Run,
  RunImpactItem,
  RunImpactItemDraft,
  RunImpactSource,
  RunImpactVerification,
  RunIntegration,
  RunIntegrationStatus,
  RunState,
  RunTrigger,
  Schedule,
  SecretRecord,
  UpdateAgentInput,
  UpdateAttemptInput,
  UpdateProjectInput,
  UpdateRunInput,
  UpdateRunIntegrationInput,
  UpdateScheduleInput,
  UpsertRunIntegrationInput,
  UpsertSecretInput,
  UserRole,
} from "@shared/entities";
