/**
 * The `.gojo/` workspace contract: which files a repository is expected to
 * commit, and which files gojo generates at run time.
 *
 * Registration files are human-authored configuration and belong in version
 * control so a checkout fully describes its agents. Generated files are
 * per-run scratch that gojo writes into the workspace and persists separately
 * as run artifacts. Committing a generated file rewrites the same path on
 * every agent branch, which makes every other open pull request conflict, so
 * gojo keeps them out of result commits regardless of a repo's `.gitignore`.
 */

/** Per-run report an agent writes for gojo to read back. */
export const HANDOFF_RELATIVE_PATH = '.gojo/handoff.json';

/** Script the shell adapter materializes from an agent prompt. */
export const RUN_SCRIPT_RELATIVE_PATH = '.gojo/run.sh';

/** Conventional location for handoff assets (long PR bodies, reports). */
export const HANDOFF_ASSETS_RELATIVE_PATH = '.gojo/assets/';

/** Immutable source issue/PR snapshot materialized for the current run. */
export const SUBJECT_CONTEXT_RELATIVE_PATH = '.gojo/context/subject.json';

/**
 * Paths gojo writes into a workspace during a run. Never committed, never
 * reported as a changed file. Directory entries end with `/`.
 */
export const GENERATED_WORKSPACE_PATHS: readonly string[] = [
  HANDOFF_RELATIVE_PATH,
  RUN_SCRIPT_RELATIVE_PATH,
  HANDOFF_ASSETS_RELATIVE_PATH,
  SUBJECT_CONTEXT_RELATIVE_PATH,
];

/**
 * Registration paths a project is expected to track. Directory entries end
 * with `/` and match everything beneath them.
 */
export const REGISTRATION_PATHS: readonly string[] = [
  'gojo.yaml',
  '.gojo/agents/',
  '.gojo/instructions.md',
  '.gojo/labels.md',
];

/**
 * The `.gitignore` block that encodes this contract: ignore everything gojo
 * generates under `.gojo/`, then re-include the registration files.
 */
export const GITIGNORE_BLOCK_HEADER = '# gojo: ignore generated run files, keep registration files';

export function gojoGitignoreBlock(): string {
  const reincludes = REGISTRATION_PATHS.filter((path) => path.startsWith('.gojo/')).flatMap(
    (path) => (path.endsWith('/') ? [`!${path}`, `!${path}**`] : [`!${path}`]),
  );
  return [GITIGNORE_BLOCK_HEADER, '.gojo/*', ...reincludes].join('\n');
}

/** True when `path` is generated by gojo inside the workspace. */
export function isGeneratedWorkspacePath(path: string): boolean {
  const normalized = path.replace(/^\.\//, '').replace(/\\/g, '/');
  return GENERATED_WORKSPACE_PATHS.some((generated) =>
    generated.endsWith('/')
      ? normalized === generated.slice(0, -1) || normalized.startsWith(generated)
      : normalized === generated,
  );
}
